### PR TITLE
Example for resizing attachment before create media

### PR DESCRIPTION
**Pull request by mingkho**
Added an example to show how to use value from Attachment control with NativeScript ImageSource to resize image before creating them as media entity.

### CODE REVIEW

**Comment by mingkho** [comment]
> Page should clearly indicate that resize is only for the first attachment, or update the rule to properly loop over all attachments and resize each one

I have added a check that will allow a maximum of 1 image per create.

**Comment by billfroelich** [comment]
We should also update the readme to indicate that the create is only for offline.  Last I checked the sample service does not allow Product creation.

**Comment by mingkho** [comment]
> Can you update below?
> In Application.app - update schema version to 6.1 (this solves the OData direct rendering schema validation in editor)

Done!

**Comment by mingkho** [comment]
> We should also update the readme to indicate that the create is only for offline. Last I checked the sample service does not allow Product creation.

Done!

**Review by jitendrakansal — APPROVED** [review]

**Pull request merged**
